public interface IPersonWarningFlag {
    /* TODO:  This class has been retired.  Delete this class ASAP.
    DateTime getEffectiveDate();
    String getFlagCode();
    String getFlagCodeDescription();
    DateTime getInactiveDate();
    String getNoteClassCode();
    String getNoteClassCodeDescription();
    String getNoteSubClassCode();
    String getNoteSubClassCodeDescription();
    String getNoteText(); */
}